#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/ssl \
  /downloads1 \
  /downloads2

# copy
if [[ ! -e /config/aria2.conf ]]
then
  cp /aria2/conf/aria2.conf.default /config/aria2.conf
fi

if [[ ! -e /config/aria2.session ]]
then
  touch /config/aria2.session
fi

if [[ ! -e /config/dht.dat ]]
then
  touch /config/dht.dat
fi

if [[ ! -e /config/log.txt ]]
then
  touch /config/log.txt
fi

# permissions
chown -R abc:abc \
	/config \
  /downloads \
  /downloads1 \
  /downloads2

chmod a+x \
  /aria2/script/delete.sh \
  /aria2/script/delete.aria2.sh \
  /aria2/script/tracker.sh

# auto updatetracker
if [ "$UpdateTracker" == "true" ]
then
  exec s6-setuidgid abc /aria2/script/tracker.sh
fi